In [1]:
from selenium import webdriver
from selenium.webdriver.common.by import By

In [2]:
driver = webdriver.Chrome()
driver.get(r"https://app.smartwealthpro.com/Account/Login")

In [ ]:
## table_datase

# muskasturid@gmail.com
# Nep@l2053
# https://app.smartwealthpro.com/Account/Login

In [ ]:
## closed ended

In [ ]:
# /html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[44]/td[10]

In [5]:
# closed ended 
all_rows=[]
for i in range(1,45):
    rows=[]
    for j in range(1,11):
        try:
            ele=driver.find_element(By.XPATH,f"//div//div//div//div//div[2]//div//table//tbody//tr[{i}]//td[{j}]")
            # print(ele.text)
            rows.append(ele.text)
        except:
            rows.append(None)
    all_rows.append(rows)
print("Extracted all the data sucessfully ")

Extracted all the data sucessfully

In [6]:
len(rows)

10

In [8]:
len(all_rows)

44

In [9]:
import pandas as pd

In [11]:
al_columns=[]
for i in range(1,11):
    cols=driver.find_element(By.XPATH,f"//table//thead//tr//th[{i}]").text
    al_columns.append(cols)

In [12]:
al_columns

['Company',
 'Fund Size',
 'Units',
 'Maturity\nDate',
 'Maturity\nPeriod',
 'Fund Managers',
 'LTP',
 'Weekly NAV\n(Rs)',
 'Weekly NAV\nDate',
 'Premium (+) or\nDiscount (-) %']

In [13]:
dfs=pd.DataFrame(all_rows)
dfs

,0,1,2,3,4,5,6,7,8,9
0,C30MF,75.07 Cr,7.51 Cr,2090-02-01 BS,10 years,Citizens Capital Limited,9.83,10.80,2083-01-25 BS,-8.98 %
1,CMF2,56.00 Cr,5.60 Cr,2083-03-24 BS,7 years,Citizens Capital Limited,9.96,10.28,2083-01-25 BS,-3.11 %
2,CSY,1.25 Arb,12.50 Cr,2092-08-09 BS,10 years,Citizens Capital Limited,9.30,9.84,2083-01-25 BS,-5.48 %
3,GBIMESY2,1.50 Arb,15.00 Cr,2092-03-22 BS,10 years,Global IME Capital Limited,9.54,10.24,2083-01-25 BS,-6.83 %
4,GIBF1,1.03 Arb,10.26 Cr,2089-03-22 BS,10 years,Global IME Capital Limited,10.72,12.00,2083-01-25 BS,-10.66 %
5,GSY,1.25 Arb,12.50 Cr,2091-09-03 BS,10 years,Garima Capital Limited,9.90,10.47,2083-02-01 BS,-5.44 %
6,H8020,1.00 Arb,10.00 Cr,2090-06-15 BS,10 years,Himalayan Capital Limited,11.85,12.64,2083-01-25 BS,-6.25 %
7,HLICF,5.00 Arb,50.00 Cr,2092-05-29 BS,10 years,Himalayan Investment Banker Limited,8.90,9.35,2082-12-27 BS,-4.81 %
8,KDBY,1.23 Arb,12.25 Cr,2089-04-10 BS,10 years,Kumari Capital Limited,11.60,12.90,2083-02-01 BS,-10.07 %
9,KEF,1.00 Arb,10.00 Cr,2087-12-03 BS,10 years,Kumari Capital Limited,10.85,12.04,2083-02-01 BS,-9.88 %
10,KSY,74.48 Cr,7.45 Cr,2090-12-05 BS,10 years,Kumari Capital Limited,9.79,10.56,2083-02-01 BS,-7.29 %
11,LUK,65.26 Cr,6.53 Cr,2087-04-29 BS,10 years,Laxmi Capital Market Limited,10.00,10.36,2083-01-18 BS,-3.47 %
12,LVF2,80.00 Cr,8.00 Cr,2090-05-18 BS,10 years,LS Capital,9.73,10.30,2083-01-18 BS,-5.53 %
13,MBLEF,1.22 Arb,12.16 Cr,2093-12-13 BS,12 years,Machhapuchchhre Capital Limited,10.01,11.01,2083-02-01 BS,-9.08 %
14,MMF1,1.25 Arb,12.50 Cr,2088-05-22 BS,10 years,NIMB Ace Capital Limited,9.33,9.76,2083-01-25 BS,-4.40 %
15,MNMF1,1.25 Arb,12.50 Cr,2091-09-03 BS,10 years,Muktinath Capital Limited,9.99,10.53,2083-02-01 BS,-5.12 %
16,NBF2,1.12 Arb,11.20 Cr,2086-02-18 BS,10 years,Nabil Investment Banking Limited,9.90,10.42,2083-02-01 BS,-4.99 %
17,NBF3,1.25 Arb,12.50 Cr,2088-06-07 BS,10 years,Nabil Investment Banking Limited,9.95,10.41,2083-02-01 BS,-4.41 %
18,NIBLGF,1.32 Arb,13.20 Cr,2089-10-04 BS,10 years,NIMB Ace Capital Limited,9.17,9.96,2083-01-25 BS,-7.93 %
19,NIBLSTF,1.13 Arb,11.30 Cr,2092-10-24 BS,12 years,NIMB Ace Capital Limited,9.11,9.79,2083-01-25 BS,-6.94 %
20,NIBSF2,1.50 Arb,15.00 Cr,2088-02-15 BS,10 years,NIMB Ace Capital Limited,9.60,9.90,2083-01-25 BS,-3.03 %
21,NICBF,75.50 Cr,7.55 Cr,2086-05-11 BS,10 years,NIC Asia Capital Limited,9.65,10.24,2083-02-01 BS,-5.76 %
22,NICFC,10.20 Cr,10.20 Cr,2086-03-01 BS,7 years,NIC Asia Capital Limited,9.30,10.21,2083-02-01 BS,-8.91 %
23,NICGF2,90.50 Cr,9.05 Cr,2087-08-04 BS,7 years,NIC Asia Capital Limited,9.39,10.26,2083-02-01 BS,-8.47 %
24,NICSF,1.25 Arb,12.50 Cr,2085-04-08 BS,7 years,NIC Asia Capital Limited,9.36,9.68,2083-01-25 BS,-3.30 %
25,NMB50,1.25 Arb,12.50 Cr,2083-05-16 BS,7 years,NMB Capital Limited,10.65,10.54,2083-02-01 BS,1.04 %
26,NMBHF2,1.36 Arb,13.65 Cr,2091-11-14 BS,10 years,NMB Capital Limited,9.76,10.57,2083-02-01 BS,-7.66 %
27,NSIF2,1.20 Arb,12.00 Cr,2089-05-16 BS,10 years,NMB Capital Limited,10.91,11.84,2083-02-01 BS,-7.85 %
28,NSY,2.00 Arb,20.00 Cr,2092-10-19 BS,10 years,Nepal Life Capital Limited,9.45,9.78,2083-01-18 BS,-3.37 %
29,PRSF,1.00 Arb,10.00 Cr,2088-11-30 BS,10 years,Prabhu Capital Limited,12.99,14.85,2083-02-01 BS,-12.52 %
30,PSF,1.25 Arb,12.50 Cr,2085-03-07 BS,7 years,Prabhu Capital Limited,12.36,13.71,2083-02-01 BS,-9.84 %
31,RBBF40,1.25 Arb,12.50 Cr,2094-05-18 BS,12 years,RBB Merchant Bank Ltd.,9.70,10.14,2083-01-25 BS,-4.33 %
32,RMF1,1.25 Arb,12.50 Cr,2085-04-08 BS,7 years,RBB Merchant Bank Ltd.,9.94,10.38,2083-01-25 BS,-4.23 %
33,RMF2,84.61 Cr,8.46 Cr,2090-02-08 BS,10 years,RBB Merchant Bank Ltd.,10.50,11.02,2083-01-25 BS,-4.71 %
34,RSY,1.20 Arb,12.00 Cr,2092-01-18 BS,10 years,Reliable Capital Investment and Merchant Limited,10.20,11.32,2083-02-01 BS,-9.89 %
35,SAGF,67.25 Cr,6.73 Cr,2090-08-12 BS,11 years,Sanima Capital Limited,10.20,10.83,2083-01-25 BS,-5.81 %
36,SBCF,1.25 Arb,12.50 Cr,2087-12-11 BS,10 years,LS Capital,9.76,10.19,2083-01-11 BS,-4.21 %
37,SEF,1.50 Arb,15.00 Cr,2084-08-22 BS,10 years,Siddhartha Capital Limited,9.95,10.66,2083-02-01 BS,-6.66 %
38,SEF2,1.00 Arb,10.00 Cr,2094-01-24 BS,12 years,Siddhartha Capital Limited,0.00,N/A,N/A,0.00 %
39,SFEF,1.00 Arb,10.00 Cr,2088-10-29 BS,10 years,LS Capital,10.15,10.90,2083-01-11 BS,-6.88 %
40,SFMF,86.00 Cr,8.60 Cr,2086-07-19 BS,10 years,LS Capital,10.20,10.60,2083-01-11 BS,-3.77 %
41,SIGS2,1.20 Arb,12.00 Cr,2086-04-08 BS,10 years,Siddhartha Capital Limited,10.51,11.24,2083-02-01 BS,-6.49 %
42,SIGS3,80.58 Cr,8.06 Cr,2090-01-17 BS,10 years,Siddhartha Capital Limited,10.85,11.90,2083-02-01 BS,-8.82 %
43,SLCF,1.20 Arb,12.00 Cr,2084-11-11 BS,7 years,Sanima Capital Limited,9.95,10.40,2083-01-25 BS,-4.32 %

In [14]:
dfs.columns=al_columns

In [16]:
dfs['type']="Closed Ended"

In [17]:
dfs

,Company,Fund Size,Units,Maturity\nDate,Maturity\nPeriod,Fund Managers,LTP,Weekly NAV\n(Rs),Weekly NAV\nDate,Premium (+) or\nDiscount (-) %,type
0,C30MF,75.07 Cr,7.51 Cr,2090-02-01 BS,10 years,Citizens Capital Limited,9.83,10.80,2083-01-25 BS,-8.98 %,Closed Ended
1,CMF2,56.00 Cr,5.60 Cr,2083-03-24 BS,7 years,Citizens Capital Limited,9.96,10.28,2083-01-25 BS,-3.11 %,Closed Ended
2,CSY,1.25 Arb,12.50 Cr,2092-08-09 BS,10 years,Citizens Capital Limited,9.30,9.84,2083-01-25 BS,-5.48 %,Closed Ended
3,GBIMESY2,1.50 Arb,15.00 Cr,2092-03-22 BS,10 years,Global IME Capital Limited,9.54,10.24,2083-01-25 BS,-6.83 %,Closed Ended
4,GIBF1,1.03 Arb,10.26 Cr,2089-03-22 BS,10 years,Global IME Capital Limited,10.72,12.00,2083-01-25 BS,-10.66 %,Closed Ended
5,GSY,1.25 Arb,12.50 Cr,2091-09-03 BS,10 years,Garima Capital Limited,9.90,10.47,2083-02-01 BS,-5.44 %,Closed Ended
6,H8020,1.00 Arb,10.00 Cr,2090-06-15 BS,10 years,Himalayan Capital Limited,11.85,12.64,2083-01-25 BS,-6.25 %,Closed Ended
7,HLICF,5.00 Arb,50.00 Cr,2092-05-29 BS,10 years,Himalayan Investment Banker Limited,8.90,9.35,2082-12-27 BS,-4.81 %,Closed Ended
8,KDBY,1.23 Arb,12.25 Cr,2089-04-10 BS,10 years,Kumari Capital Limited,11.60,12.90,2083-02-01 BS,-10.07 %,Closed Ended
9,KEF,1.00 Arb,10.00 Cr,2087-12-03 BS,10 years,Kumari Capital Limited,10.85,12.04,2083-02-01 BS,-9.88 %,Closed Ended
10,KSY,74.48 Cr,7.45 Cr,2090-12-05 BS,10 years,Kumari Capital Limited,9.79,10.56,2083-02-01 BS,-7.29 %,Closed Ended
11,LUK,65.26 Cr,6.53 Cr,2087-04-29 BS,10 years,Laxmi Capital Market Limited,10.00,10.36,2083-01-18 BS,-3.47 %,Closed Ended
12,LVF2,80.00 Cr,8.00 Cr,2090-05-18 BS,10 years,LS Capital,9.73,10.30,2083-01-18 BS,-5.53 %,Closed Ended
13,MBLEF,1.22 Arb,12.16 Cr,2093-12-13 BS,12 years,Machhapuchchhre Capital Limited,10.01,11.01,2083-02-01 BS,-9.08 %,Closed Ended
14,MMF1,1.25 Arb,12.50 Cr,2088-05-22 BS,10 years,NIMB Ace Capital Limited,9.33,9.76,2083-01-25 BS,-4.40 %,Closed Ended
15,MNMF1,1.25 Arb,12.50 Cr,2091-09-03 BS,10 years,Muktinath Capital Limited,9.99,10.53,2083-02-01 BS,-5.12 %,Closed Ended
16,NBF2,1.12 Arb,11.20 Cr,2086-02-18 BS,10 years,Nabil Investment Banking Limited,9.90,10.42,2083-02-01 BS,-4.99 %,Closed Ended
17,NBF3,1.25 Arb,12.50 Cr,2088-06-07 BS,10 years,Nabil Investment Banking Limited,9.95,10.41,2083-02-01 BS,-4.41 %,Closed Ended
18,NIBLGF,1.32 Arb,13.20 Cr,2089-10-04 BS,10 years,NIMB Ace Capital Limited,9.17,9.96,2083-01-25 BS,-7.93 %,Closed Ended
19,NIBLSTF,1.13 Arb,11.30 Cr,2092-10-24 BS,12 years,NIMB Ace Capital Limited,9.11,9.79,2083-01-25 BS,-6.94 %,Closed Ended
20,NIBSF2,1.50 Arb,15.00 Cr,2088-02-15 BS,10 years,NIMB Ace Capital Limited,9.60,9.90,2083-01-25 BS,-3.03 %,Closed Ended
21,NICBF,75.50 Cr,7.55 Cr,2086-05-11 BS,10 years,NIC Asia Capital Limited,9.65,10.24,2083-02-01 BS,-5.76 %,Closed Ended
22,NICFC,10.20 Cr,10.20 Cr,2086-03-01 BS,7 years,NIC Asia Capital Limited,9.30,10.21,2083-02-01 BS,-8.91 %,Closed Ended
23,NICGF2,90.50 Cr,9.05 Cr,2087-08-04 BS,7 years,NIC Asia Capital Limited,9.39,10.26,2083-02-01 BS,-8.47 %,Closed Ended
24,NICSF,1.25 Arb,12.50 Cr,2085-04-08 BS,7 years,NIC Asia Capital Limited,9.36,9.68,2083-01-25 BS,-3.30 %,Closed Ended
25,NMB50,1.25 Arb,12.50 Cr,2083-05-16 BS,7 years,NMB Capital Limited,10.65,10.54,2083-02-01 BS,1.04 %,Closed Ended
26,NMBHF2,1.36 Arb,13.65 Cr,2091-11-14 BS,10 years,NMB Capital Limited,9.76,10.57,2083-02-01 BS,-7.66 %,Closed Ended
27,NSIF2,1.20 Arb,12.00 Cr,2089-05-16 BS,10 years,NMB Capital Limited,10.91,11.84,2083-02-01 BS,-7.85 %,Closed Ended
28,NSY,2.00 Arb,20.00 Cr,2092-10-19 BS,10 years,Nepal Life Capital Limited,9.45,9.78,2083-01-18 BS,-3.37 %,Closed Ended
29,PRSF,1.00 Arb,10.00 Cr,2088-11-30 BS,10 years,Prabhu Capital Limited,12.99,14.85,2083-02-01 BS,-12.52 %,Closed Ended
30,PSF,1.25 Arb,12.50 Cr,2085-03-07 BS,7 years,Prabhu Capital Limited,12.36,13.71,2083-02-01 BS,-9.84 %,Closed Ended
31,RBBF40,1.25 Arb,12.50 Cr,2094-05-18 BS,12 years,RBB Merchant Bank Ltd.,9.70,10.14,2083-01-25 BS,-4.33 %,Closed Ended
32,RMF1,1.25 Arb,12.50 Cr,2085-04-08 BS,7 years,RBB Merchant Bank Ltd.,9.94,10.38,2083-01-25 BS,-4.23 %,Closed Ended
33,RMF2,84.61 Cr,8.46 Cr,2090-02-08 BS,10 years,RBB Merchant Bank Ltd.,10.50,11.02,2083-01-25 BS,-4.71 %,Closed Ended
34,RSY,1.20 Arb,12.00 Cr,2092-01-18 BS,10 years,Reliable Capital Investment and Merchant Limited,10.20,11.32,2083-02-01 BS,-9.89 %,Closed Ended
35,SAGF,67.25 Cr,6.73 Cr,2090-08-12 BS,11 years,Sanima Capital Limited,10.20,10.83,2083-01-25 BS,-5.81 %,Closed Ended
36,SBCF,1.25 Arb,12.50 Cr,2087-12-11 BS,10 years,LS Capital,9.76,10.19,2083-01-11 BS,-4.21 %,Closed Ended
37,SEF,1.50 Arb,15.00 Cr,2084-08-22 BS,10 years,Siddhartha Capital Limited,9.95,10.66,2083-02-01 BS,-6.66 %,Closed Ended
38,SEF2,1.00 Arb,10.00 Cr,2094-01-24 BS,12 years,Siddhartha Capital Limited,0.00,N/A,N/A,0.00 %,Closed Ended
39,SFEF,1.00 Arb,10.00 Cr,2088-10-29 BS,10 years,LS Capital,10.15,10.90,2083-01-11 BS,-6.88 %,Closed Ended
40,SFMF,86.00 Cr,8.60 Cr,2086-07-19 BS,10 years,LS Capital,10.20,10.60,2083-01-11 BS,-3.77 %,Closed Ended
41,SIGS2,1.20 Arb,12.00 Cr,2086-04-08 BS,10 years,Siddhartha Capital Limited,10.51,11.24,2083-02-01 BS,-6.49 %,Closed Ended
42,SIGS3,80.58 Cr,8.06 Cr,2090-01-17 BS,10 years,Siddhartha Capital Limited,10.85,11.90,2083-02-01 BS,-8.82 %,Closed Ended
43,SLCF,1.20 Arb,12.00 Cr,2084-11-11 BS,7 years,Sanima Capital Limited,9.95,10.40,2083-01-25 BS,-4.32 %,Closed Ended

In [ ]:
## Open ended

In [18]:
all_rows=[]
for i in range(1,12):
    rows=[]
    for j in range(1,7):
        try:
            ele=driver.find_element(By.XPATH,f"//div//div//div//div//div[2]//div//table//tbody//tr[{i}]//td[{j}]")
            # print(ele.text)
            rows.append(ele.text)
        except:
            rows.append(None)
    all_rows.append(rows)
print("Extracted all the data sucessfully ")

Extracted all the data sucessfully

In [ ]:
/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/thead/tr/th[6]

In [25]:
columns=[]
for i in range(1,7):
    cols=driver.find_element(By.XPATH,f"/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/thead/tr/th[{i}]").text
    columns.append(cols)
columns

['Company',
 'Fund Size',
 'Units',
 'Fund Managers',
 'Weekly NAV\n(Rs)',
 'Weekly NAV\nDate']

In [ ]:
/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/thead/tr/th[6]

In [26]:
opens=pd.DataFrame(all_rows)
opens.columns=columns
opens

,Company,Fund Size,Units,Fund Managers,Weekly NAV\n(Rs),Weekly NAV\nDate
0,CSBY,50.00 Cr,5.00 Cr,Citizens Capital Limited,10.33,2083-01-25 BS
1,ELIS,1.00 Arb,10.00 Cr,NIC Asia Capital Limited,9.84,2083-02-01 BS
2,KSLY,1.00 Arb,10.00 Cr,Kumari Capital Limited,12.13,2083-02-01 BS
3,NADDF,2.00 Arb,20.00 Cr,NIC Asia Capital Limited,10.00,2083-02-01 BS
4,NFCF,2.25 Arb,22.50 Cr,Nabil Investment Banking Limited,10.45,2083-02-01 BS
5,NI31,25.00 Cr,2.50 Cr,Nabil Investment Banking Limited,10.34,2083-02-01 BS
6,NIBLSF,6.00 Arb,60.00 Cr,NIMB Ace Capital Limited,10.25,2083-01-25 BS
7,NMBSBF,1.00 Arb,10.00 Cr,NMB Capital Limited,10.72,2083-02-01 BS
8,SFF,1.00 Arb,10.00 Cr,Sanima Capital Limited,10.48,2083-02-01 BS
9,SLK,1.00 Arb,10.00 Cr,Laxmi Capital Market Limited,10.40,2083-01-25 BS
10,SSIS,2.80 Arb,28.00 Cr,Siddhartha Capital Limited,11.01,2083-02-01 BS

In [27]:
opens['type']="Open-Ended"

In [ ]:
# /html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[11]/td[6]

In [29]:
dfs

,Company,Fund Size,Units,Maturity\nDate,Maturity\nPeriod,Fund Managers,LTP,Weekly NAV\n(Rs),Weekly NAV\nDate,Premium (+) or\nDiscount (-) %,type
0,C30MF,75.07 Cr,7.51 Cr,2090-02-01 BS,10 years,Citizens Capital Limited,9.83,10.80,2083-01-25 BS,-8.98 %,Closed Ended
1,CMF2,56.00 Cr,5.60 Cr,2083-03-24 BS,7 years,Citizens Capital Limited,9.96,10.28,2083-01-25 BS,-3.11 %,Closed Ended
2,CSY,1.25 Arb,12.50 Cr,2092-08-09 BS,10 years,Citizens Capital Limited,9.30,9.84,2083-01-25 BS,-5.48 %,Closed Ended
3,GBIMESY2,1.50 Arb,15.00 Cr,2092-03-22 BS,10 years,Global IME Capital Limited,9.54,10.24,2083-01-25 BS,-6.83 %,Closed Ended
4,GIBF1,1.03 Arb,10.26 Cr,2089-03-22 BS,10 years,Global IME Capital Limited,10.72,12.00,2083-01-25 BS,-10.66 %,Closed Ended
5,GSY,1.25 Arb,12.50 Cr,2091-09-03 BS,10 years,Garima Capital Limited,9.90,10.47,2083-02-01 BS,-5.44 %,Closed Ended
6,H8020,1.00 Arb,10.00 Cr,2090-06-15 BS,10 years,Himalayan Capital Limited,11.85,12.64,2083-01-25 BS,-6.25 %,Closed Ended
7,HLICF,5.00 Arb,50.00 Cr,2092-05-29 BS,10 years,Himalayan Investment Banker Limited,8.90,9.35,2082-12-27 BS,-4.81 %,Closed Ended
8,KDBY,1.23 Arb,12.25 Cr,2089-04-10 BS,10 years,Kumari Capital Limited,11.60,12.90,2083-02-01 BS,-10.07 %,Closed Ended
9,KEF,1.00 Arb,10.00 Cr,2087-12-03 BS,10 years,Kumari Capital Limited,10.85,12.04,2083-02-01 BS,-9.88 %,Closed Ended
10,KSY,74.48 Cr,7.45 Cr,2090-12-05 BS,10 years,Kumari Capital Limited,9.79,10.56,2083-02-01 BS,-7.29 %,Closed Ended
11,LUK,65.26 Cr,6.53 Cr,2087-04-29 BS,10 years,Laxmi Capital Market Limited,10.00,10.36,2083-01-18 BS,-3.47 %,Closed Ended
12,LVF2,80.00 Cr,8.00 Cr,2090-05-18 BS,10 years,LS Capital,9.73,10.30,2083-01-18 BS,-5.53 %,Closed Ended
13,MBLEF,1.22 Arb,12.16 Cr,2093-12-13 BS,12 years,Machhapuchchhre Capital Limited,10.01,11.01,2083-02-01 BS,-9.08 %,Closed Ended
14,MMF1,1.25 Arb,12.50 Cr,2088-05-22 BS,10 years,NIMB Ace Capital Limited,9.33,9.76,2083-01-25 BS,-4.40 %,Closed Ended
15,MNMF1,1.25 Arb,12.50 Cr,2091-09-03 BS,10 years,Muktinath Capital Limited,9.99,10.53,2083-02-01 BS,-5.12 %,Closed Ended
16,NBF2,1.12 Arb,11.20 Cr,2086-02-18 BS,10 years,Nabil Investment Banking Limited,9.90,10.42,2083-02-01 BS,-4.99 %,Closed Ended
17,NBF3,1.25 Arb,12.50 Cr,2088-06-07 BS,10 years,Nabil Investment Banking Limited,9.95,10.41,2083-02-01 BS,-4.41 %,Closed Ended
18,NIBLGF,1.32 Arb,13.20 Cr,2089-10-04 BS,10 years,NIMB Ace Capital Limited,9.17,9.96,2083-01-25 BS,-7.93 %,Closed Ended
19,NIBLSTF,1.13 Arb,11.30 Cr,2092-10-24 BS,12 years,NIMB Ace Capital Limited,9.11,9.79,2083-01-25 BS,-6.94 %,Closed Ended
20,NIBSF2,1.50 Arb,15.00 Cr,2088-02-15 BS,10 years,NIMB Ace Capital Limited,9.60,9.90,2083-01-25 BS,-3.03 %,Closed Ended
21,NICBF,75.50 Cr,7.55 Cr,2086-05-11 BS,10 years,NIC Asia Capital Limited,9.65,10.24,2083-02-01 BS,-5.76 %,Closed Ended
22,NICFC,10.20 Cr,10.20 Cr,2086-03-01 BS,7 years,NIC Asia Capital Limited,9.30,10.21,2083-02-01 BS,-8.91 %,Closed Ended
23,NICGF2,90.50 Cr,9.05 Cr,2087-08-04 BS,7 years,NIC Asia Capital Limited,9.39,10.26,2083-02-01 BS,-8.47 %,Closed Ended
24,NICSF,1.25 Arb,12.50 Cr,2085-04-08 BS,7 years,NIC Asia Capital Limited,9.36,9.68,2083-01-25 BS,-3.30 %,Closed Ended
25,NMB50,1.25 Arb,12.50 Cr,2083-05-16 BS,7 years,NMB Capital Limited,10.65,10.54,2083-02-01 BS,1.04 %,Closed Ended
26,NMBHF2,1.36 Arb,13.65 Cr,2091-11-14 BS,10 years,NMB Capital Limited,9.76,10.57,2083-02-01 BS,-7.66 %,Closed Ended
27,NSIF2,1.20 Arb,12.00 Cr,2089-05-16 BS,10 years,NMB Capital Limited,10.91,11.84,2083-02-01 BS,-7.85 %,Closed Ended
28,NSY,2.00 Arb,20.00 Cr,2092-10-19 BS,10 years,Nepal Life Capital Limited,9.45,9.78,2083-01-18 BS,-3.37 %,Closed Ended
29,PRSF,1.00 Arb,10.00 Cr,2088-11-30 BS,10 years,Prabhu Capital Limited,12.99,14.85,2083-02-01 BS,-12.52 %,Closed Ended
30,PSF,1.25 Arb,12.50 Cr,2085-03-07 BS,7 years,Prabhu Capital Limited,12.36,13.71,2083-02-01 BS,-9.84 %,Closed Ended
31,RBBF40,1.25 Arb,12.50 Cr,2094-05-18 BS,12 years,RBB Merchant Bank Ltd.,9.70,10.14,2083-01-25 BS,-4.33 %,Closed Ended
32,RMF1,1.25 Arb,12.50 Cr,2085-04-08 BS,7 years,RBB Merchant Bank Ltd.,9.94,10.38,2083-01-25 BS,-4.23 %,Closed Ended
33,RMF2,84.61 Cr,8.46 Cr,2090-02-08 BS,10 years,RBB Merchant Bank Ltd.,10.50,11.02,2083-01-25 BS,-4.71 %,Closed Ended
34,RSY,1.20 Arb,12.00 Cr,2092-01-18 BS,10 years,Reliable Capital Investment and Merchant Limited,10.20,11.32,2083-02-01 BS,-9.89 %,Closed Ended
35,SAGF,67.25 Cr,6.73 Cr,2090-08-12 BS,11 years,Sanima Capital Limited,10.20,10.83,2083-01-25 BS,-5.81 %,Closed Ended
36,SBCF,1.25 Arb,12.50 Cr,2087-12-11 BS,10 years,LS Capital,9.76,10.19,2083-01-11 BS,-4.21 %,Closed Ended
37,SEF,1.50 Arb,15.00 Cr,2084-08-22 BS,10 years,Siddhartha Capital Limited,9.95,10.66,2083-02-01 BS,-6.66 %,Closed Ended
38,SEF2,1.00 Arb,10.00 Cr,2094-01-24 BS,12 years,Siddhartha Capital Limited,0.00,N/A,N/A,0.00 %,Closed Ended
39,SFEF,1.00 Arb,10.00 Cr,2088-10-29 BS,10 years,LS Capital,10.15,10.90,2083-01-11 BS,-6.88 %,Closed Ended
40,SFMF,86.00 Cr,8.60 Cr,2086-07-19 BS,10 years,LS Capital,10.20,10.60,2083-01-11 BS,-3.77 %,Closed Ended
41,SIGS2,1.20 Arb,12.00 Cr,2086-04-08 BS,10 years,Siddhartha Capital Limited,10.51,11.24,2083-02-01 BS,-6.49 %,Closed Ended
42,SIGS3,80.58 Cr,8.06 Cr,2090-01-17 BS,10 years,Siddhartha Capital Limited,10.85,11.90,2083-02-01 BS,-8.82 %,Closed Ended
43,SLCF,1.20 Arb,12.00 Cr,2084-11-11 BS,7 years,Sanima Capital Limited,9.95,10.40,2083-01-25 BS,-4.32 %,Closed Ended

In [28]:
opens

,Company,Fund Size,Units,Fund Managers,Weekly NAV\n(Rs),Weekly NAV\nDate,type
0,CSBY,50.00 Cr,5.00 Cr,Citizens Capital Limited,10.33,2083-01-25 BS,Open-Ended
1,ELIS,1.00 Arb,10.00 Cr,NIC Asia Capital Limited,9.84,2083-02-01 BS,Open-Ended
2,KSLY,1.00 Arb,10.00 Cr,Kumari Capital Limited,12.13,2083-02-01 BS,Open-Ended
3,NADDF,2.00 Arb,20.00 Cr,NIC Asia Capital Limited,10.00,2083-02-01 BS,Open-Ended
4,NFCF,2.25 Arb,22.50 Cr,Nabil Investment Banking Limited,10.45,2083-02-01 BS,Open-Ended
5,NI31,25.00 Cr,2.50 Cr,Nabil Investment Banking Limited,10.34,2083-02-01 BS,Open-Ended
6,NIBLSF,6.00 Arb,60.00 Cr,NIMB Ace Capital Limited,10.25,2083-01-25 BS,Open-Ended
7,NMBSBF,1.00 Arb,10.00 Cr,NMB Capital Limited,10.72,2083-02-01 BS,Open-Ended
8,SFF,1.00 Arb,10.00 Cr,Sanima Capital Limited,10.48,2083-02-01 BS,Open-Ended
9,SLK,1.00 Arb,10.00 Cr,Laxmi Capital Market Limited,10.40,2083-01-25 BS,Open-Ended
10,SSIS,2.80 Arb,28.00 Cr,Siddhartha Capital Limited,11.01,2083-02-01 BS,Open-Ended

In [ ]:
# matured

In [ ]:
/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[9]/td[8]/span

In [ ]:
# /html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[9]/td[8]/span

In [36]:
all_rows=[]
for i in range(1,10):
    rows=[]
    for j in range(1,9):
        try:
            ele=driver.find_element(By.XPATH,f"//div//div//div//div//div[2]//div//table//tbody//tr[{i}]//td[{j}]")
            # print(ele.text)
            rows.append(ele.text)
        except:
            rows.append(None)
    all_rows.append(rows)
print("Extracted all the data sucessfully ")

Extracted all the data sucessfully

In [ ]:
/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/thead/tr/th[8]

In [41]:
columns=[]
for i in range(1,9):
    cols=driver.find_element(By.XPATH,f"//div//div[2]//div//table//thead//tr//th[{i}]").text
    columns.append(cols)
columns

['Company',
 'Fund Size',
 'Units',
 'Maturity\nDate',
 'Maturity\nPeriod',
 'Fund Managers',
 'Weekly NAV\n(Rs)',
 'Weekly NAV\nDate']

In [42]:
matured=pd.DataFrame(all_rows)
matured.columns=columns

In [45]:
matured['type']="matured"

In [43]:
dfs

,Company,Fund Size,Units,Maturity\nDate,Maturity\nPeriod,Fund Managers,LTP,Weekly NAV\n(Rs),Weekly NAV\nDate,Premium (+) or\nDiscount (-) %,type
0,C30MF,75.07 Cr,7.51 Cr,2090-02-01 BS,10 years,Citizens Capital Limited,9.83,10.80,2083-01-25 BS,-8.98 %,Closed Ended
1,CMF2,56.00 Cr,5.60 Cr,2083-03-24 BS,7 years,Citizens Capital Limited,9.96,10.28,2083-01-25 BS,-3.11 %,Closed Ended
2,CSY,1.25 Arb,12.50 Cr,2092-08-09 BS,10 years,Citizens Capital Limited,9.30,9.84,2083-01-25 BS,-5.48 %,Closed Ended
3,GBIMESY2,1.50 Arb,15.00 Cr,2092-03-22 BS,10 years,Global IME Capital Limited,9.54,10.24,2083-01-25 BS,-6.83 %,Closed Ended
4,GIBF1,1.03 Arb,10.26 Cr,2089-03-22 BS,10 years,Global IME Capital Limited,10.72,12.00,2083-01-25 BS,-10.66 %,Closed Ended
5,GSY,1.25 Arb,12.50 Cr,2091-09-03 BS,10 years,Garima Capital Limited,9.90,10.47,2083-02-01 BS,-5.44 %,Closed Ended
6,H8020,1.00 Arb,10.00 Cr,2090-06-15 BS,10 years,Himalayan Capital Limited,11.85,12.64,2083-01-25 BS,-6.25 %,Closed Ended
7,HLICF,5.00 Arb,50.00 Cr,2092-05-29 BS,10 years,Himalayan Investment Banker Limited,8.90,9.35,2082-12-27 BS,-4.81 %,Closed Ended
8,KDBY,1.23 Arb,12.25 Cr,2089-04-10 BS,10 years,Kumari Capital Limited,11.60,12.90,2083-02-01 BS,-10.07 %,Closed Ended
9,KEF,1.00 Arb,10.00 Cr,2087-12-03 BS,10 years,Kumari Capital Limited,10.85,12.04,2083-02-01 BS,-9.88 %,Closed Ended
10,KSY,74.48 Cr,7.45 Cr,2090-12-05 BS,10 years,Kumari Capital Limited,9.79,10.56,2083-02-01 BS,-7.29 %,Closed Ended
11,LUK,65.26 Cr,6.53 Cr,2087-04-29 BS,10 years,Laxmi Capital Market Limited,10.00,10.36,2083-01-18 BS,-3.47 %,Closed Ended
12,LVF2,80.00 Cr,8.00 Cr,2090-05-18 BS,10 years,LS Capital,9.73,10.30,2083-01-18 BS,-5.53 %,Closed Ended
13,MBLEF,1.22 Arb,12.16 Cr,2093-12-13 BS,12 years,Machhapuchchhre Capital Limited,10.01,11.01,2083-02-01 BS,-9.08 %,Closed Ended
14,MMF1,1.25 Arb,12.50 Cr,2088-05-22 BS,10 years,NIMB Ace Capital Limited,9.33,9.76,2083-01-25 BS,-4.40 %,Closed Ended
15,MNMF1,1.25 Arb,12.50 Cr,2091-09-03 BS,10 years,Muktinath Capital Limited,9.99,10.53,2083-02-01 BS,-5.12 %,Closed Ended
16,NBF2,1.12 Arb,11.20 Cr,2086-02-18 BS,10 years,Nabil Investment Banking Limited,9.90,10.42,2083-02-01 BS,-4.99 %,Closed Ended
17,NBF3,1.25 Arb,12.50 Cr,2088-06-07 BS,10 years,Nabil Investment Banking Limited,9.95,10.41,2083-02-01 BS,-4.41 %,Closed Ended
18,NIBLGF,1.32 Arb,13.20 Cr,2089-10-04 BS,10 years,NIMB Ace Capital Limited,9.17,9.96,2083-01-25 BS,-7.93 %,Closed Ended
19,NIBLSTF,1.13 Arb,11.30 Cr,2092-10-24 BS,12 years,NIMB Ace Capital Limited,9.11,9.79,2083-01-25 BS,-6.94 %,Closed Ended
20,NIBSF2,1.50 Arb,15.00 Cr,2088-02-15 BS,10 years,NIMB Ace Capital Limited,9.60,9.90,2083-01-25 BS,-3.03 %,Closed Ended
21,NICBF,75.50 Cr,7.55 Cr,2086-05-11 BS,10 years,NIC Asia Capital Limited,9.65,10.24,2083-02-01 BS,-5.76 %,Closed Ended
22,NICFC,10.20 Cr,10.20 Cr,2086-03-01 BS,7 years,NIC Asia Capital Limited,9.30,10.21,2083-02-01 BS,-8.91 %,Closed Ended
23,NICGF2,90.50 Cr,9.05 Cr,2087-08-04 BS,7 years,NIC Asia Capital Limited,9.39,10.26,2083-02-01 BS,-8.47 %,Closed Ended
24,NICSF,1.25 Arb,12.50 Cr,2085-04-08 BS,7 years,NIC Asia Capital Limited,9.36,9.68,2083-01-25 BS,-3.30 %,Closed Ended
25,NMB50,1.25 Arb,12.50 Cr,2083-05-16 BS,7 years,NMB Capital Limited,10.65,10.54,2083-02-01 BS,1.04 %,Closed Ended
26,NMBHF2,1.36 Arb,13.65 Cr,2091-11-14 BS,10 years,NMB Capital Limited,9.76,10.57,2083-02-01 BS,-7.66 %,Closed Ended
27,NSIF2,1.20 Arb,12.00 Cr,2089-05-16 BS,10 years,NMB Capital Limited,10.91,11.84,2083-02-01 BS,-7.85 %,Closed Ended
28,NSY,2.00 Arb,20.00 Cr,2092-10-19 BS,10 years,Nepal Life Capital Limited,9.45,9.78,2083-01-18 BS,-3.37 %,Closed Ended
29,PRSF,1.00 Arb,10.00 Cr,2088-11-30 BS,10 years,Prabhu Capital Limited,12.99,14.85,2083-02-01 BS,-12.52 %,Closed Ended
30,PSF,1.25 Arb,12.50 Cr,2085-03-07 BS,7 years,Prabhu Capital Limited,12.36,13.71,2083-02-01 BS,-9.84 %,Closed Ended
31,RBBF40,1.25 Arb,12.50 Cr,2094-05-18 BS,12 years,RBB Merchant Bank Ltd.,9.70,10.14,2083-01-25 BS,-4.33 %,Closed Ended
32,RMF1,1.25 Arb,12.50 Cr,2085-04-08 BS,7 years,RBB Merchant Bank Ltd.,9.94,10.38,2083-01-25 BS,-4.23 %,Closed Ended
33,RMF2,84.61 Cr,8.46 Cr,2090-02-08 BS,10 years,RBB Merchant Bank Ltd.,10.50,11.02,2083-01-25 BS,-4.71 %,Closed Ended
34,RSY,1.20 Arb,12.00 Cr,2092-01-18 BS,10 years,Reliable Capital Investment and Merchant Limited,10.20,11.32,2083-02-01 BS,-9.89 %,Closed Ended
35,SAGF,67.25 Cr,6.73 Cr,2090-08-12 BS,11 years,Sanima Capital Limited,10.20,10.83,2083-01-25 BS,-5.81 %,Closed Ended
36,SBCF,1.25 Arb,12.50 Cr,2087-12-11 BS,10 years,LS Capital,9.76,10.19,2083-01-11 BS,-4.21 %,Closed Ended
37,SEF,1.50 Arb,15.00 Cr,2084-08-22 BS,10 years,Siddhartha Capital Limited,9.95,10.66,2083-02-01 BS,-6.66 %,Closed Ended
38,SEF2,1.00 Arb,10.00 Cr,2094-01-24 BS,12 years,Siddhartha Capital Limited,0.00,N/A,N/A,0.00 %,Closed Ended
39,SFEF,1.00 Arb,10.00 Cr,2088-10-29 BS,10 years,LS Capital,10.15,10.90,2083-01-11 BS,-6.88 %,Closed Ended
40,SFMF,86.00 Cr,8.60 Cr,2086-07-19 BS,10 years,LS Capital,10.20,10.60,2083-01-11 BS,-3.77 %,Closed Ended
41,SIGS2,1.20 Arb,12.00 Cr,2086-04-08 BS,10 years,Siddhartha Capital Limited,10.51,11.24,2083-02-01 BS,-6.49 %,Closed Ended
42,SIGS3,80.58 Cr,8.06 Cr,2090-01-17 BS,10 years,Siddhartha Capital Limited,10.85,11.90,2083-02-01 BS,-8.82 %,Closed Ended
43,SLCF,1.20 Arb,12.00 Cr,2084-11-11 BS,7 years,Sanima Capital Limited,9.95,10.40,2083-01-25 BS,-4.32 %,Closed Ended

In [46]:
matured

,Company,Fund Size,Units,Maturity\nDate,Maturity\nPeriod,Fund Managers,Weekly NAV\n(Rs),Weekly NAV\nDate,type
0,LEMF,1.25 Arb,12.50 Cr,2081-02-30 BS,7 years,Laxmi Capital Market Limited,9.97,2081-02-25 BS,matured
1,LVF1,50.00 Cr,5.00 Cr,2076-12-12 BS,5 years,Laxmi Capital Market Limited,N/A,N/A,matured
2,NEF,1.25 Arb,12.50 Cr,2080-07-20 BS,7 years,Nabil Investment Banking Limited,10.31,2080-07-17 BS,matured
3,NIBLPF,75.00 Cr,7.50 Cr,2080-09-26 BS,7 years,NIBL Ace Capital Limited,9.81,2080-09-27 BS,matured
4,NICGF,83.52 Cr,8.35 Cr,2081-11-28 BS,7 years,NIC Asia Capital Limited,11.49,2081-12-22 BS,matured
5,NMBHF1,1.00 Arb,10.00 Cr,2080-07-09 BS,7 years,NMB Capital Limited,10.16,2080-07-03 BS,matured
6,SAEF,1.30 Arb,13.00 Cr,2081-09-11 BS,7 years,Sanima Capital Limited,11.64,2081-09-26 BS,matured
7,SEOS,1.00 Arb,10.00 Cr,2076-04-06 BS,5 years,Siddhartha Capital Limited,N/A,N/A,matured
8,SIGS1,4.00 Cr,40.00 L,2074-01-13 BS,5 years,Siddhartha Capital Limited,N/A,N/A,matured

In [47]:
opens

,Company,Fund Size,Units,Fund Managers,Weekly NAV\n(Rs),Weekly NAV\nDate,type
0,CSBY,50.00 Cr,5.00 Cr,Citizens Capital Limited,10.33,2083-01-25 BS,Open-Ended
1,ELIS,1.00 Arb,10.00 Cr,NIC Asia Capital Limited,9.84,2083-02-01 BS,Open-Ended
2,KSLY,1.00 Arb,10.00 Cr,Kumari Capital Limited,12.13,2083-02-01 BS,Open-Ended
3,NADDF,2.00 Arb,20.00 Cr,NIC Asia Capital Limited,10.00,2083-02-01 BS,Open-Ended
4,NFCF,2.25 Arb,22.50 Cr,Nabil Investment Banking Limited,10.45,2083-02-01 BS,Open-Ended
5,NI31,25.00 Cr,2.50 Cr,Nabil Investment Banking Limited,10.34,2083-02-01 BS,Open-Ended
6,NIBLSF,6.00 Arb,60.00 Cr,NIMB Ace Capital Limited,10.25,2083-01-25 BS,Open-Ended
7,NMBSBF,1.00 Arb,10.00 Cr,NMB Capital Limited,10.72,2083-02-01 BS,Open-Ended
8,SFF,1.00 Arb,10.00 Cr,Sanima Capital Limited,10.48,2083-02-01 BS,Open-Ended
9,SLK,1.00 Arb,10.00 Cr,Laxmi Capital Market Limited,10.40,2083-01-25 BS,Open-Ended
10,SSIS,2.80 Arb,28.00 Cr,Siddhartha Capital Limited,11.01,2083-02-01 BS,Open-Ended

In [48]:
dfs

,Company,Fund Size,Units,Maturity\nDate,Maturity\nPeriod,Fund Managers,LTP,Weekly NAV\n(Rs),Weekly NAV\nDate,Premium (+) or\nDiscount (-) %,type
0,C30MF,75.07 Cr,7.51 Cr,2090-02-01 BS,10 years,Citizens Capital Limited,9.83,10.80,2083-01-25 BS,-8.98 %,Closed Ended
1,CMF2,56.00 Cr,5.60 Cr,2083-03-24 BS,7 years,Citizens Capital Limited,9.96,10.28,2083-01-25 BS,-3.11 %,Closed Ended
2,CSY,1.25 Arb,12.50 Cr,2092-08-09 BS,10 years,Citizens Capital Limited,9.30,9.84,2083-01-25 BS,-5.48 %,Closed Ended
3,GBIMESY2,1.50 Arb,15.00 Cr,2092-03-22 BS,10 years,Global IME Capital Limited,9.54,10.24,2083-01-25 BS,-6.83 %,Closed Ended
4,GIBF1,1.03 Arb,10.26 Cr,2089-03-22 BS,10 years,Global IME Capital Limited,10.72,12.00,2083-01-25 BS,-10.66 %,Closed Ended
5,GSY,1.25 Arb,12.50 Cr,2091-09-03 BS,10 years,Garima Capital Limited,9.90,10.47,2083-02-01 BS,-5.44 %,Closed Ended
6,H8020,1.00 Arb,10.00 Cr,2090-06-15 BS,10 years,Himalayan Capital Limited,11.85,12.64,2083-01-25 BS,-6.25 %,Closed Ended
7,HLICF,5.00 Arb,50.00 Cr,2092-05-29 BS,10 years,Himalayan Investment Banker Limited,8.90,9.35,2082-12-27 BS,-4.81 %,Closed Ended
8,KDBY,1.23 Arb,12.25 Cr,2089-04-10 BS,10 years,Kumari Capital Limited,11.60,12.90,2083-02-01 BS,-10.07 %,Closed Ended
9,KEF,1.00 Arb,10.00 Cr,2087-12-03 BS,10 years,Kumari Capital Limited,10.85,12.04,2083-02-01 BS,-9.88 %,Closed Ended
10,KSY,74.48 Cr,7.45 Cr,2090-12-05 BS,10 years,Kumari Capital Limited,9.79,10.56,2083-02-01 BS,-7.29 %,Closed Ended
11,LUK,65.26 Cr,6.53 Cr,2087-04-29 BS,10 years,Laxmi Capital Market Limited,10.00,10.36,2083-01-18 BS,-3.47 %,Closed Ended
12,LVF2,80.00 Cr,8.00 Cr,2090-05-18 BS,10 years,LS Capital,9.73,10.30,2083-01-18 BS,-5.53 %,Closed Ended
13,MBLEF,1.22 Arb,12.16 Cr,2093-12-13 BS,12 years,Machhapuchchhre Capital Limited,10.01,11.01,2083-02-01 BS,-9.08 %,Closed Ended
14,MMF1,1.25 Arb,12.50 Cr,2088-05-22 BS,10 years,NIMB Ace Capital Limited,9.33,9.76,2083-01-25 BS,-4.40 %,Closed Ended
15,MNMF1,1.25 Arb,12.50 Cr,2091-09-03 BS,10 years,Muktinath Capital Limited,9.99,10.53,2083-02-01 BS,-5.12 %,Closed Ended
16,NBF2,1.12 Arb,11.20 Cr,2086-02-18 BS,10 years,Nabil Investment Banking Limited,9.90,10.42,2083-02-01 BS,-4.99 %,Closed Ended
17,NBF3,1.25 Arb,12.50 Cr,2088-06-07 BS,10 years,Nabil Investment Banking Limited,9.95,10.41,2083-02-01 BS,-4.41 %,Closed Ended
18,NIBLGF,1.32 Arb,13.20 Cr,2089-10-04 BS,10 years,NIMB Ace Capital Limited,9.17,9.96,2083-01-25 BS,-7.93 %,Closed Ended
19,NIBLSTF,1.13 Arb,11.30 Cr,2092-10-24 BS,12 years,NIMB Ace Capital Limited,9.11,9.79,2083-01-25 BS,-6.94 %,Closed Ended
20,NIBSF2,1.50 Arb,15.00 Cr,2088-02-15 BS,10 years,NIMB Ace Capital Limited,9.60,9.90,2083-01-25 BS,-3.03 %,Closed Ended
21,NICBF,75.50 Cr,7.55 Cr,2086-05-11 BS,10 years,NIC Asia Capital Limited,9.65,10.24,2083-02-01 BS,-5.76 %,Closed Ended
22,NICFC,10.20 Cr,10.20 Cr,2086-03-01 BS,7 years,NIC Asia Capital Limited,9.30,10.21,2083-02-01 BS,-8.91 %,Closed Ended
23,NICGF2,90.50 Cr,9.05 Cr,2087-08-04 BS,7 years,NIC Asia Capital Limited,9.39,10.26,2083-02-01 BS,-8.47 %,Closed Ended
24,NICSF,1.25 Arb,12.50 Cr,2085-04-08 BS,7 years,NIC Asia Capital Limited,9.36,9.68,2083-01-25 BS,-3.30 %,Closed Ended
25,NMB50,1.25 Arb,12.50 Cr,2083-05-16 BS,7 years,NMB Capital Limited,10.65,10.54,2083-02-01 BS,1.04 %,Closed Ended
26,NMBHF2,1.36 Arb,13.65 Cr,2091-11-14 BS,10 years,NMB Capital Limited,9.76,10.57,2083-02-01 BS,-7.66 %,Closed Ended
27,NSIF2,1.20 Arb,12.00 Cr,2089-05-16 BS,10 years,NMB Capital Limited,10.91,11.84,2083-02-01 BS,-7.85 %,Closed Ended
28,NSY,2.00 Arb,20.00 Cr,2092-10-19 BS,10 years,Nepal Life Capital Limited,9.45,9.78,2083-01-18 BS,-3.37 %,Closed Ended
29,PRSF,1.00 Arb,10.00 Cr,2088-11-30 BS,10 years,Prabhu Capital Limited,12.99,14.85,2083-02-01 BS,-12.52 %,Closed Ended
30,PSF,1.25 Arb,12.50 Cr,2085-03-07 BS,7 years,Prabhu Capital Limited,12.36,13.71,2083-02-01 BS,-9.84 %,Closed Ended
31,RBBF40,1.25 Arb,12.50 Cr,2094-05-18 BS,12 years,RBB Merchant Bank Ltd.,9.70,10.14,2083-01-25 BS,-4.33 %,Closed Ended
32,RMF1,1.25 Arb,12.50 Cr,2085-04-08 BS,7 years,RBB Merchant Bank Ltd.,9.94,10.38,2083-01-25 BS,-4.23 %,Closed Ended
33,RMF2,84.61 Cr,8.46 Cr,2090-02-08 BS,10 years,RBB Merchant Bank Ltd.,10.50,11.02,2083-01-25 BS,-4.71 %,Closed Ended
34,RSY,1.20 Arb,12.00 Cr,2092-01-18 BS,10 years,Reliable Capital Investment and Merchant Limited,10.20,11.32,2083-02-01 BS,-9.89 %,Closed Ended
35,SAGF,67.25 Cr,6.73 Cr,2090-08-12 BS,11 years,Sanima Capital Limited,10.20,10.83,2083-01-25 BS,-5.81 %,Closed Ended
36,SBCF,1.25 Arb,12.50 Cr,2087-12-11 BS,10 years,LS Capital,9.76,10.19,2083-01-11 BS,-4.21 %,Closed Ended
37,SEF,1.50 Arb,15.00 Cr,2084-08-22 BS,10 years,Siddhartha Capital Limited,9.95,10.66,2083-02-01 BS,-6.66 %,Closed Ended
38,SEF2,1.00 Arb,10.00 Cr,2094-01-24 BS,12 years,Siddhartha Capital Limited,0.00,N/A,N/A,0.00 %,Closed Ended
39,SFEF,1.00 Arb,10.00 Cr,2088-10-29 BS,10 years,LS Capital,10.15,10.90,2083-01-11 BS,-6.88 %,Closed Ended
40,SFMF,86.00 Cr,8.60 Cr,2086-07-19 BS,10 years,LS Capital,10.20,10.60,2083-01-11 BS,-3.77 %,Closed Ended
41,SIGS2,1.20 Arb,12.00 Cr,2086-04-08 BS,10 years,Siddhartha Capital Limited,10.51,11.24,2083-02-01 BS,-6.49 %,Closed Ended
42,SIGS3,80.58 Cr,8.06 Cr,2090-01-17 BS,10 years,Siddhartha Capital Limited,10.85,11.90,2083-02-01 BS,-8.82 %,Closed Ended
43,SLCF,1.20 Arb,12.00 Cr,2084-11-11 BS,7 years,Sanima Capital Limited,9.95,10.40,2083-01-25 BS,-4.32 %,Closed Ended

In [49]:
dfs.to_csv(r"C:\Users\HP\Desktop\data_extractions\extraced_datasets\closed_ended.csv",index=False)
opens.to_csv(r"C:\Users\HP\Desktop\data_extractions\extraced_datasets\open_ended.csv",index=False)
matured.to_csv(r"C:\Users\HP\Desktop\data_extractions\extraced_datasets\matured.csv",index=False)

## saves the dta ainto the json formats

In [54]:
dfs.to_json(r"C:\Users\HP\Desktop\data_extractions\extraced_datasets\closed_ended.json",index=False,indent=4,orient="records")
opens.to_json(r"C:\Users\HP\Desktop\data_extractions\extraced_datasets\open_ended.json",index=False,indent=4,orient="records")
matured.to_json(r"C:\Users\HP\Desktop\data_extractions\extraced_datasets\matured.json",index=False,indent=4,orient="records")

## Noew the extract the data of the internals company

## Extract tthe first Company URLS

In [ ]:
## closed ended urls

In [ ]:
div/div/div/div[2]/div/table/tbody/tr[44]/td[1]/a[1]

In [ ]:
open ended urls

In [ ]:
/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[11]/td[1]/a

In [ ]:
# matured ended urls

In [ ]:
/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[9]/td[1]/a

In [57]:
closed_urls=[]
for i in range(1,45):
    company=driver.find_element(By.XPATH,f"/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[{i}]/td[1]/a[1]").get_attribute("href")
    closed_urls.append(company)
closed_urls

['https://app.smartwealthpro.com/Company/Overview/Citizens-Super-30-Mutual-Fund/C30MF?c=885',
 'https://app.smartwealthpro.com/Company/Overview/Citizens-Mutual-Fund-2/CMF2?c=184',
 'https://app.smartwealthpro.com/Company/Overview/Citizens-Santulit-Yojana/CSY?c=1096',
 'https://app.smartwealthpro.com/Company/Overview/Global-IME-Sammunat-Yojana2/GBIMESY2?c=1092',
 'https://app.smartwealthpro.com/Company/Overview/Global-IME-Balanced-Fund--1/GIBF1?c=815',
 'https://app.smartwealthpro.com/Company/Overview/Garima-Samriddhi-Yojana/GSY?c=1049',
 'https://app.smartwealthpro.com/Company/Overview/Himalayan-8020/H8020?c=935',
 'https://app.smartwealthpro.com/Company/Overview/HLI-Large-Cap-Fund/HLICF?c=1091',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Dhanabriddhi-Yojana/KDBY?c=797',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Equity-Fund/KEF?c=729',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Sabal-Yojana/KSY?c=956',
 'https://app.smartwealthpro.com/Company/Overview/Laxmi-Unnati-Kosh/LUK?c=598',
 'https://app.smartwealthpro.com/Company/Overview/Laxmi-Value-Fund-II/LVF2?c=923',
 'https://app.smartwealthpro.com/Company/Overview/MBL-Equity-Fund/MBLEF?c=1070',
 'https://app.smartwealthpro.com/Company/Overview/Mega-Mutual-Fund--1/MMF1?c=764',
 'https://app.smartwealthpro.com/Company/Overview/Muktinath-Mutual-Fund-1/MNMF1?c=982',
 'https://app.smartwealthpro.com/Company/Overview/Nabil-Balanced-Fund-2/NBF2?c=188',
 'https://app.smartwealthpro.com/Company/Overview/Nabil-Balanced-Fund-III/NBF3?c=768',
 'https://app.smartwealthpro.com/Company/Overview/NIBL-Growth-Fund/NIBLGF?c=849',
 'https://app.smartwealthpro.com/Company/Overview/NIBL-Stable-Fund/NIBLSTF?c=954',
 'https://app.smartwealthpro.com/Company/Overview/NIBL-Samriddhi-Fund--II/NIBSF2?c=728',
 'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Balanced-Fund/NICBF?c=192',
 'https://app.smartwealthpro.com/Company/Overview/NIC-ASIA-Flexi-CAP-Fund/NICFC?c=798',
 'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Growth-Fund2/NICGF2?c=949',
 'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Select30/NICSF?c=735',
 'https://app.smartwealthpro.com/Company/Overview/NMB-50/NMB50?c=597',
 'https://app.smartwealthpro.com/Company/Overview/NMB-Hydrid-Fund-LII/NMBHF2?c=1066',
 'https://app.smartwealthpro.com/Company/Overview/NMB-Sulav-Investment-Fund--II/NSIF2?c=824',
 'https://app.smartwealthpro.com/Company/Overview/Nepal-Life-Samriddhi-Lagani-Yojana/NSY?c=1097',
 'https://app.smartwealthpro.com/Company/Overview/Prabhu-Smart-Fund/PRSF?c=881',
 'https://app.smartwealthpro.com/Company/Overview/Prabhu-Select-Fund/PSF?c=734',
 'https://app.smartwealthpro.com/Company/Overview/RBB-Focus-40/RBBF40?c=1090',
 'https://app.smartwealthpro.com/Company/Overview/RBB-Mutual-Fund-1/RMF1?c=736',
 'https://app.smartwealthpro.com/Company/Overview/RBB-Mutual-Fund-2/RMF2?c=884',
 'https://app.smartwealthpro.com/Company/Overview/Reliable-Samriddhi-Yojana/RSY?c=1072',
 'https://app.smartwealthpro.com/Company/Overview/Sanima-Growth-Fund/SAGF?c=833',
 'https://app.smartwealthpro.com/Company/Overview/Sunrise-Bluechip-Fund/SBCF?c=720',
 'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Equity-Fund/SEF?c=197',
 'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Equity-Fund-2/SEF2?c=1102',
 'https://app.smartwealthpro.com/Company/Overview/Sunrise-Focused-Equity-Fund/SFEF?c=850',
 'https://app.smartwealthpro.com/Company/Overview/Sunrise-First-Mutual-Fund/SFMF?c=200',
 'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Investment-Growth-Scheme--2/SIGS2?c=199',
 'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Investment-Growth-Scheme3/SIGS3?c=878',
 'https://app.smartwealthpro.com/Company/Overview/Sanima-Large-Cap-Fund/SLCF?c=629']

In [61]:
open_urls=[]
for i in range(1,12):
    company=driver.find_element(By.XPATH,f"/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[{i}]/td[1]/a").get_attribute("href")
    open_urls.append(company)
open_urls

['https://app.smartwealthpro.com/Company/Overview/Citizens-Sadabahar-Yojana/CSBY?c=1082',
 'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Equity-Linked-Investment-Scheme/ELIS?c=1087',
 'https://app.smartwealthpro.com/Company/Overview/Kumari-Sunaulo-Lagani-Yojana/KSLY?c=874',
 'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Dynamic-Debt-Fund/NADDF?c=622',
 'https://app.smartwealthpro.com/Company/Overview/Nabil-Flexi-Cap-Fund/NFCF?c=836',
 'https://app.smartwealthpro.com/Company/Overview/NI-31/NI31?c=1088',
 'https://app.smartwealthpro.com/Company/Overview/NIBL-Sahabhagita-Fund/NIBLSF?c=601',
 'https://app.smartwealthpro.com/Company/Overview/NMB-Saral-Bachat-Fund--E-Open-End/NMBSBF?c=737',
 'https://app.smartwealthpro.com/Company/Overview/Sanima-Flexi-Fund/SFF?c=1067',
 'https://app.smartwealthpro.com/Company/Overview/Subha-Laxmi-Kosh/SLK?c=821',
 'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Systematic-Investment-Scheme/SSIS?c=747']

# matured urls

In [ ]:
/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[9]/td[1]/a

In [62]:
matured_urls=[]
for i in range(1,10):
    company=driver.find_element(By.XPATH,f"/html/body/div[6]/div/div/div/div/div[2]/div/div[2]/div/div/div/div/div[2]/div/table/tbody/tr[{i}]/td[1]/a").get_attribute("href")
    matured_urls.append(company)
matured_urls

['https://app.smartwealthpro.com/Company/Overview/Laxmi-Equity-Fund/LEMF?c=186',
 'https://app.smartwealthpro.com/Company/Overview/Laxmi-Value-Fund1/LVF1?c=187',
 'https://app.smartwealthpro.com/Company/Overview/Nabil-Equity-Fund/NEF?c=189',
 'https://app.smartwealthpro.com/Company/Overview/NIBL-Pragati-Fund/NIBLPF?c=190',
 'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Growth-Fund/NICGF?c=193',
 'https://app.smartwealthpro.com/Company/Overview/NMB-Hybrid-Fund-L1/NMBHF1?c=194',
 'https://app.smartwealthpro.com/Company/Overview/Sanima-Equity-Fund/SAEF?c=196',
 'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Equity-Orineted-Scheme/SEOS?c=198',
 'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Investment-Growth-Scheme1/SIGS1?c=521']

In [63]:
all_urls={"closed_urls":closed_urls,"open_urls":open_urls,"matured_urls":matured_urls}
all_urls

{'closed_urls': ['https://app.smartwealthpro.com/Company/Overview/Citizens-Super-30-Mutual-Fund/C30MF?c=885',
  'https://app.smartwealthpro.com/Company/Overview/Citizens-Mutual-Fund-2/CMF2?c=184',
  'https://app.smartwealthpro.com/Company/Overview/Citizens-Santulit-Yojana/CSY?c=1096',
  'https://app.smartwealthpro.com/Company/Overview/Global-IME-Sammunat-Yojana2/GBIMESY2?c=1092',
  'https://app.smartwealthpro.com/Company/Overview/Global-IME-Balanced-Fund--1/GIBF1?c=815',
  'https://app.smartwealthpro.com/Company/Overview/Garima-Samriddhi-Yojana/GSY?c=1049',
  'https://app.smartwealthpro.com/Company/Overview/Himalayan-8020/H8020?c=935',
  'https://app.smartwealthpro.com/Company/Overview/HLI-Large-Cap-Fund/HLICF?c=1091',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Dhanabriddhi-Yojana/KDBY?c=797',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Equity-Fund/KEF?c=729',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Sabal-Yojana/KSY?c=956',
  'https://app.smartwealthpro.com/Company/Overview/Laxmi-Unnati-Kosh/LUK?c=598',
  'https://app.smartwealthpro.com/Company/Overview/Laxmi-Value-Fund-II/LVF2?c=923',
  'https://app.smartwealthpro.com/Company/Overview/MBL-Equity-Fund/MBLEF?c=1070',
  'https://app.smartwealthpro.com/Company/Overview/Mega-Mutual-Fund--1/MMF1?c=764',
  'https://app.smartwealthpro.com/Company/Overview/Muktinath-Mutual-Fund-1/MNMF1?c=982',
  'https://app.smartwealthpro.com/Company/Overview/Nabil-Balanced-Fund-2/NBF2?c=188',
  'https://app.smartwealthpro.com/Company/Overview/Nabil-Balanced-Fund-III/NBF3?c=768',
  'https://app.smartwealthpro.com/Company/Overview/NIBL-Growth-Fund/NIBLGF?c=849',
  'https://app.smartwealthpro.com/Company/Overview/NIBL-Stable-Fund/NIBLSTF?c=954',
  'https://app.smartwealthpro.com/Company/Overview/NIBL-Samriddhi-Fund--II/NIBSF2?c=728',
  'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Balanced-Fund/NICBF?c=192',
  'https://app.smartwealthpro.com/Company/Overview/NIC-ASIA-Flexi-CAP-Fund/NICFC?c=798',
  'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Growth-Fund2/NICGF2?c=949',
  'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Select30/NICSF?c=735',
  'https://app.smartwealthpro.com/Company/Overview/NMB-50/NMB50?c=597',
  'https://app.smartwealthpro.com/Company/Overview/NMB-Hydrid-Fund-LII/NMBHF2?c=1066',
  'https://app.smartwealthpro.com/Company/Overview/NMB-Sulav-Investment-Fund--II/NSIF2?c=824',
  'https://app.smartwealthpro.com/Company/Overview/Nepal-Life-Samriddhi-Lagani-Yojana/NSY?c=1097',
  'https://app.smartwealthpro.com/Company/Overview/Prabhu-Smart-Fund/PRSF?c=881',
  'https://app.smartwealthpro.com/Company/Overview/Prabhu-Select-Fund/PSF?c=734',
  'https://app.smartwealthpro.com/Company/Overview/RBB-Focus-40/RBBF40?c=1090',
  'https://app.smartwealthpro.com/Company/Overview/RBB-Mutual-Fund-1/RMF1?c=736',
  'https://app.smartwealthpro.com/Company/Overview/RBB-Mutual-Fund-2/RMF2?c=884',
  'https://app.smartwealthpro.com/Company/Overview/Reliable-Samriddhi-Yojana/RSY?c=1072',
  'https://app.smartwealthpro.com/Company/Overview/Sanima-Growth-Fund/SAGF?c=833',
  'https://app.smartwealthpro.com/Company/Overview/Sunrise-Bluechip-Fund/SBCF?c=720',
  'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Equity-Fund/SEF?c=197',
  'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Equity-Fund-2/SEF2?c=1102',
  'https://app.smartwealthpro.com/Company/Overview/Sunrise-Focused-Equity-Fund/SFEF?c=850',
  'https://app.smartwealthpro.com/Company/Overview/Sunrise-First-Mutual-Fund/SFMF?c=200',
  'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Investment-Growth-Scheme--2/SIGS2?c=199',
  'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Investment-Growth-Scheme3/SIGS3?c=878',
  'https://app.smartwealthpro.com/Company/Overview/Sanima-Large-Cap-Fund/SLCF?c=629'],
 'open_urls': ['https://app.smartwealthpro.com/Company/Overview/Citizens-Sadabahar-Yojana/CSBY?c=1082',
  'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Equity-Linked-Investment-Scheme/ELIS?c=1087',
  'https://app.smartwealthpro.com/Company/Overview/Kumari-Sunaulo-Lagani-Yojana/KSLY?c=874',
  'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Dynamic-Debt-Fund/NADDF?c=622',
  'https://app.smartwealthpro.com/Company/Overview/Nabil-Flexi-Cap-Fund/NFCF?c=836',
  'https://app.smartwealthpro.com/Company/Overview/NI-31/NI31?c=1088',
  'https://app.smartwealthpro.com/Company/Overview/NIBL-Sahabhagita-Fund/NIBLSF?c=601',
  'https://app.smartwealthpro.com/Company/Overview/NMB-Saral-Bachat-Fund--E-Open-End/NMBSBF?c=737',
  'https://app.smartwealthpro.com/Company/Overview/Sanima-Flexi-Fund/SFF?c=1067',
  'https://app.smartwealthpro.com/Company/Overview/Subha-Laxmi-Kosh/SLK?c=821',
  'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Systematic-Investment-Scheme/SSIS?c=747'],
 'matured_urls': ['https://app.smartwealthpro.com/Company/Overview/Laxmi-Equity-Fund/LEMF?c=186',
  'https://app.smartwealthpro.com/Company/Overview/Laxmi-Value-Fund1/LVF1?c=187',
  'https://app.smartwealthpro.com/Company/Overview/Nabil-Equity-Fund/NEF?c=189',
  'https://app.smartwealthpro.com/Company/Overview/NIBL-Pragati-Fund/NIBLPF?c=190',
  'https://app.smartwealthpro.com/Company/Overview/NIC-Asia-Growth-Fund/NICGF?c=193',
  'https://app.smartwealthpro.com/Company/Overview/NMB-Hybrid-Fund-L1/NMBHF1?c=194',
  'https://app.smartwealthpro.com/Company/Overview/Sanima-Equity-Fund/SAEF?c=196',
  'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Equity-Orineted-Scheme/SEOS?c=198',
  'https://app.smartwealthpro.com/Company/Overview/Siddhartha-Investment-Growth-Scheme1/SIGS1?c=521']}

In [66]:
import pickle 

with open(r"C:\Users\HP\Desktop\data_extractions\extraced_datasets\all_c_urls.pkl", "wb") as file:
    pickle.dump(all_urls, file)
print("dump the files sucessfully")

dump the files sucessfully

In [67]:
import os
os.getcwd()

'C:\\Users\\HP\\Desktop\\data_extractions'